name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: crazy-max/ghaction-docker-buildx@v1.0.5
      - uses: actions/checkout@v1
      - name: Login to Docker
        run: docker login -u halftome -p ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push the Docker images
        run: docker buildx build --file docker/Dockerfile --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6 -t halftome/transmission-daemon --push .